/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/subtele.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.subtele.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module subtele.yang */
public class subtele extends ConfNamespace {
    public static final int hash = 1283026158;
    public int hash() {
        return subtele.hash;
    }

    public static final String id = "http://com/example/subtele";
    public String id() {
        return subtele.id;
    }

    public static final String uri = "http://com/example/subtele";
    public String uri() {
        return subtele.uri;
    }

    public static final String prefix = "subtele";
    public String prefix() {
        return subtele.prefix;
    }

    public subtele() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _tele_visual = 1859108362;
    public static final String _tele_visual_ = "tele_visual";
    public static final int    _destination_group = 1598383525;
    public static final String _destination_group_ = "destination-group";
    public static final int    _config_data = 294526531;
    public static final String _config_data_ = "config-data";
    public static final int    _heartbeat_interval = 1281304246;
    public static final String _heartbeat_interval_ = "heartbeat-interval";
    public static final int    _clear = 634788371;
    public static final String _clear_ = "clear";
    public static final int    _queue_item = 1872384595;
    public static final String _queue_item_ = "queue-item";
    public static final int    _native = 472211213;
    public static final String _native_ = "native";
    public static final int    _sensor_group = 521692491;
    public static final String _sensor_group_ = "sensor-group";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _get_modifications = 1195376060;
    public static final String _get_modifications_ = "get-modifications";
    public static final int    _destination_id = 2142582101;
    public static final String _destination_id_ = "destination-id";
    public static final int    _time_out_choice = 1405068132;
    public static final String _time_out_choice_ = "time-out-choice";
    public static final int    _no_overwrite = 2064525500;
    public static final String _no_overwrite_ = "no-overwrite";
    public static final int    _deep = 28591482;
    public static final String _deep_ = "deep";
    public static final int    _sample_interval = 1730479987;
    public static final String _sample_interval_ = "sample-interval";
    public static final int    _ignore_refcount = 911461978;
    public static final String _ignore_refcount_ = "ignore-refcount";
    public static final int    _re_deploy = 1952857006;
    public static final String _re_deploy_ = "re-deploy";
    public static final int    _sensor_id = 1224166134;
    public static final String _sensor_id_ = "sensor-id";
    public static final int    _no_networking = 479600569;
    public static final String _no_networking_ = "no-networking";
    public static final int    _sensor_path = 424127023;
    public static final String _sensor_path_ = "sensor-path";
    public static final int    _destination = 1426812369;
    public static final String _destination_ = "destination";
    public static final int    _supress_redundant = 977054464;
    public static final String _supress_redundant_ = "supress-redundant";
    public static final int    _protocol = 943257313;
    public static final String _protocol_ = "protocol";
    public static final int    _cleared_by_admin = 1307536695;
    public static final String _cleared_by_admin_ = "cleared-by-admin";
    public static final int    _subtele = 1812597714;
    public static final String _subtele_ = "subtele";
    public static final int    _devices = 270307409;
    public static final String _devices_ = "devices";
    public static final int    _device_list = 96950231;
    public static final String _device_list_ = "device-list";
    public static final int    _result_xml = 558977045;
    public static final String _result_xml_ = "result-xml";
    public static final int    _time = 190171445;
    public static final String _time_ = "time";
    public static final int    _latest_commit_params = 654521209;
    public static final String _latest_commit_params_ = "latest-commit-params";
    public static final int    _reactive_re_deploy = 98937259;
    public static final String _reactive_re_deploy_ = "reactive-re-deploy";
    public static final int    _error = 126243105;
    public static final String _error_ = "error";
    public static final int    _source_id = 1130614059;
    public static final String _source_id_ = "source-id";
    public static final int    _in_sync = 1179976821;
    public static final String _in_sync_ = "in-sync";
    public static final int    _enable = 448570367;
    public static final String _enable_ = "enable";
    public static final int    _encoding = 180862443;
    public static final String _encoding_ = "encoding";
    public static final int    _outformat = 2033658489;
    public static final String _outformat_ = "outformat";
    public static final int    _failed_device = 1735357793;
    public static final String _failed_device_ = "failed-device";
    public static final int    _commit_queue = 159457261;
    public static final String _commit_queue_ = "commit-queue";
    public static final int    _lock = 95781586;
    public static final String _lock_ = "lock";
    public static final int    _message = 1674281495;
    public static final String _message_ = "message";
    public static final int    _shallow = 848144988;
    public static final String _shallow_ = "shallow";
    public static final int    _no_out_of_sync_check = 1635449845;
    public static final String _no_out_of_sync_check_ = "no-out-of-sync-check";
    public static final int    _purge = 521476653;
    public static final String _purge_ = "purge";
    public static final int    _diff_set = 545581821;
    public static final String _diff_set_ = "diff-set";
    public static final int    _block_others = 1263742525;
    public static final String _block_others_ = "block-others";
    public static final int    _success = 87922769;
    public static final String _success_ = "success";
    public static final int    _service_list = 1799855391;
    public static final String _service_list_ = "service-list";
    public static final int    _operation_mode = 53338359;
    public static final String _operation_mode_ = "operation-mode";
    public static final int    _device_modifications = 2139467807;
    public static final String _device_modifications_ = "device-modifications";
    public static final int    _no_of_impacted_services = 617426878;
    public static final String _no_of_impacted_services_ = "no-of-impacted-services";
    public static final int    _modified = 431631821;
    public static final String _modified_ = "modified";
    public static final int    _sync = 2047869128;
    public static final String _sync_ = "sync";
    public static final int    _dry_run = 1450488329;
    public static final String _dry_run_ = "dry-run";
    public static final int    _un_deploy = 1885839871;
    public static final String _un_deploy_ = "un-deploy";
    public static final int    _no_revision_drop = 355519481;
    public static final String _no_revision_drop_ = "no-revision-drop";
    public static final int    _subscription_id = 1687818382;
    public static final String _subscription_id_ = "subscription-id";
    public static final int    _bypass = 1000536498;
    public static final String _bypass_ = "bypass";
    public static final int    _property = 1802560321;
    public static final String _property_ = "property";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _directly_modified = 1044842587;
    public static final String _directly_modified_ = "directly-modified";
    public static final int    _forward_diff_set = 236345226;
    public static final String _forward_diff_set_ = "forward-diff-set";
    public static final int    _cli = 1771971819;
    public static final String _cli_ = "cli";
    public static final int    _tag = 21925559;
    public static final String _tag_ = "tag";
    public static final int    _source_qos_marking = 1759577328;
    public static final String _source_qos_marking_ = "source-qos-marking";
    public static final int    _depth = 664239201;
    public static final String _depth_ = "depth";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _async = 1368962940;
    public static final String _async_ = "async";
    public static final int    _re_deploy_counter = 1940885313;
    public static final String _re_deploy_counter_ = "re-deploy-counter";
    public static final int    _infinity = 1378257424;
    public static final String _infinity_ = "infinity";
    public static final int    _self_test = 1297848528;
    public static final String _self_test_ = "self-test";
    public static final int    _latest_u_info = 1742023338;
    public static final String _latest_u_info_ = "latest-u-info";
    public static final int    _used_by_customer_service = 1598928830;
    public static final String _used_by_customer_service_ = "used-by-customer-service";
    public static final int    _private = 2025604902;
    public static final String _private_ = "private";
    public static final int    _check_sync = 1337316030;
    public static final String _check_sync_ = "check-sync";
    public static final int    _timeout = 614210192;
    public static final String _timeout_ = "timeout";
    public static final int    _property_list = 1324655271;
    public static final String _property_list_ = "property-list";
    public static final int    _services = 284312249;
    public static final String _services_ = "services";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _reverse = 1011351090;
    public static final String _reverse_ = "reverse";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _data = 535242711;
    public static final String _data_ = "data";
    public static final int    _source_group = 1037723237;
    public static final String _source_group_ = "source-group";
    public static final int    _deep_check_sync = 928241134;
    public static final String _deep_check_sync_ = "deep-check-sync";
    public static final String actionpoint_telemetry_self_test = "telemetry-self-test";
    public static final String callpoint_ncs_rfs_service_hook = "ncs-rfs-service-hook";
    public static final String servicepoint_subtele_servicepoint = "subtele-servicepoint";
}
