/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/mdt.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.mdt.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module mdt.yang */
public class mdt extends ConfNamespace {
    public static final int hash = 861911684;
    public int hash() {
        return mdt.hash;
    }

    public static final String id = "http://cisco.com/ns/yang/Cisco-IOS-XR-telemetry-model-driven-cfg";
    public String id() {
        return mdt.id;
    }

    public static final String uri = "http://cisco.com/ns/yang/Cisco-IOS-XR-telemetry-model-driven-cfg";
    public String uri() {
        return mdt.uri;
    }

    public static final String prefix = "telemetry-model-driven-cfg";
    public String prefix() {
        return mdt.prefix;
    }

    public mdt() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _destination_group = 1598383525;
    public static final String _destination_group_ = "destination-group";
    public static final int    _heartbeat_interval = 1281304246;
    public static final String _heartbeat_interval_ = "heartbeat-interval";
    public static final int    _sensor_group = 521692491;
    public static final String _sensor_group_ = "sensor-group";
    public static final int    _destination_id = 2142582101;
    public static final String _destination_id_ = "destination-id";
    public static final int    _ip_address = 36594129;
    public static final String _ip_address_ = "ip-address";
    public static final int    _sample_interval = 1730479987;
    public static final String _sample_interval_ = "sample-interval";
    public static final int    _sensor_paths = 1692117363;
    public static final String _sensor_paths_ = "sensor-paths";
    public static final int    _telemetry_sensor_path = 2004072205;
    public static final String _telemetry_sensor_path_ = "telemetry-sensor-path";
    public static final int    _sensor_path = 424127023;
    public static final String _sensor_path_ = "sensor-path";
    public static final int    _destination = 1426812369;
    public static final String _destination_ = "destination";
    public static final int    _supress_redundant = 977054464;
    public static final String _supress_redundant_ = "supress-redundant";
    public static final int    _protocol = 943257313;
    public static final String _protocol_ = "protocol";
    public static final int    _telemetry_model_driven = 362813461;
    public static final String _telemetry_model_driven_ = "telemetry-model-driven";
    public static final int    _destination_groups = 676110724;
    public static final String _destination_groups_ = "destination-groups";
    public static final int    _destination_profiles = 2132573896;
    public static final String _destination_profiles_ = "destination-profiles";
    public static final int    _sensor_profiles = 2055311817;
    public static final String _sensor_profiles_ = "sensor-profiles";
    public static final int    _subscription = 982993959;
    public static final String _subscription_ = "subscription";
    public static final int    _enable = 448570367;
    public static final String _enable_ = "enable";
    public static final int    _address_family = 203507431;
    public static final String _address_family_ = "address-family";
    public static final int    _encoding = 180862443;
    public static final String _encoding_ = "encoding";
    public static final int    _ipv6 = 1228132394;
    public static final String _ipv6_ = "ipv6";
    public static final int    _ipv4_address = 400734928;
    public static final String _ipv4_address_ = "ipv4-address";
    public static final int    _destination_profile = 220558990;
    public static final String _destination_profile_ = "destination-profile";
    public static final int    _sensor_groups = 1378032050;
    public static final String _sensor_groups_ = "sensor-groups";
    public static final int    _sensor_profile = 1970107157;
    public static final String _sensor_profile_ = "sensor-profile";
    public static final int    _destinations = 1001041063;
    public static final String _destinations_ = "destinations";
    public static final int    _ipv6_address = 731894850;
    public static final String _ipv6_address_ = "ipv6-address";
    public static final int    _sensor_group_identifier = 1984724865;
    public static final String _sensor_group_identifier_ = "sensor-group-identifier";
    public static final int    _destination_port = 1685436757;
    public static final String _destination_port_ = "destination-port";
    public static final int    _source_qos_marking = 1759577328;
    public static final String _source_qos_marking_ = "source-qos-marking";
    public static final int    _subscriptions = 886823438;
    public static final String _subscriptions_ = "subscriptions";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _subscription_identifier = 1474774972;
    public static final String _subscription_identifier_ = "subscription-identifier";
    public static final int    _sensorgroupid = 1996937720;
    public static final String _sensorgroupid_ = "sensorgroupid";
    public static final int    _source_address = 554848846;
    public static final String _source_address_ = "source-address";
}
